import type { NextPage } from 'next';
import Head from 'next/head';
import { useTheme } from '@woo-pdf/contexts';

import styles from '@woo-pdf/styles/Home.module.css';

const Home: NextPage = () => {
  const { theme, toggleTheme } = useTheme();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <button className={styles.button} onClick={toggleTheme}>
            toggle {theme}
          </button>
        </p>
      </main>
    </div>
  );
};

export default Home;
