import type { NextPage } from 'next';
import Head from 'next/head';
import { Breadcrumbs, FolderCardList } from '@woo-pdf/components';

import s from '@woo-pdf/styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={s.container}>
      <Head>
        <title>Woo Pdf</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <aside>aside</aside>
      <main className={s.main}>
        <Breadcrumbs />
        <FolderCardList />
      </main>
    </div>
  );
};

export default Home;
